import type { Metadata } from 'next';
import { Montserrat } from 'next/font/google';
import Sidebar from './components/Sidebar';
import './globals.css';

const montserrat = Montserrat({
  variable: '--font-montserrat',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.variable} bg-lightOlive antialiased flex w-screen h-screen justify-center items-center `}
      >
        <div className="flex gap-6 w-5/6 h-5/6">
          <Sidebar />

          <main className="flex-1 p-6 bg-olive rounded-xl ">
            <div className="p-8 bg-beige rounded-xl shadow-md  ">
              {children}
            </div>
          </main>
        </div>
      </body>
    </html>
  );
}
